### PR TITLE
1.19.4

### PR DESCRIPTION
**Pull request by MeeniMc**
- Update to 1.19.4
added access wideners to access now package-protected methods

fixes: #61

### CODE REVIEW

**Comment by MeeniMc** [comment]
Compiles but not tested because depends on currently not released amecs-api.

**Comment by MeeniMc** [comment]
Verified it works with the new amecs-api you generated.

**Comment by Whitebrim** [comment]
@MeeniMc can you please send me artifact? dev@brim.ml

**Comment by MeeniMc** [comment]
@Whitebrim https://github.com/MeeniMc/amecs/releases/tag/v1.3.9.rc.1%2B1.19.4 for testing only

**Comment by MeeniMc** [comment]
I have been using this PR for more than a month in a variety of scenarios without any problems.

**Review by Siphalor — APPROVED** [review]
Thanks for the work, the update is looking good :+1:

**Pull request merged**
